// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn1kCjDpIi_ICVCRszqoIJS5O2V0m7J6g',
    appId: '1:457059753287:web:2853545baf7aff8f608062',
    messagingSenderId: '457059753287',
    projectId: 'manifest-bef81',
    authDomain: 'manifest-bef81.firebaseapp.com',
    storageBucket: 'manifest-bef81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn1kCjDpIi_ICVCRszqoIJS5O2V0m7J6g',
    appId: '1:457059753287:android:2853545baf7aff8f608062',
    messagingSenderId: '457059753287',
    projectId: 'manifest-bef81',
    storageBucket: 'manifest-bef81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1kCjDpIi_ICVCRszqoIJS5O2V0m7J6g',
    appId: '1:457059753287:ios:2853545baf7aff8f608062',
    messagingSenderId: '457059753287',
    projectId: 'manifest-bef81',
    storageBucket: 'manifest-bef81.firebasestorage.app',
    iosBundleId: 'manifest.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn1kCjDpIi_ICVCRszqoIJS5O2V0m7J6g',
    appId: '1:457059753287:ios:2853545baf7aff8f608062',
    messagingSenderId: '457059753287',
    projectId: 'manifest-bef81',
    storageBucket: 'manifest-bef81.firebasestorage.app',
    iosBundleId: 'manifest.app',
  );
} 